### ISSUE TITLE
Не собирается под Windows 7

### ISSUE THREAD

**Issue by terbooter** [vsuharnikov/sypexgeo-node#13]
```
dima@COSMOS C:\ubuntu\js\platform-js\node_modules\sypexgeo-vyvid
$ if not defined npm_config_node_gyp (node "C:\Users\dima\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\ubuntu\js\platform-js\node_modules\sypexgeo-vyvid\build\..\src\xyz\vyvid\sypexgeo\uint24_t.h
C:\ubuntu\js\platform-js\node_modules\sypexgeo-vyvid\build\..\src\xyz\vyvid\sypexgeo\util\string_builder.h
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  sypexgeo_node.cc
  db.cc
  location.cc
  win_delay_load_hook.cc
..\src\xyz\vyvid\sypexgeo\db.cc(10): fatal error C1083: Cannot open include file: 'arpa/inet.h': No such file or directory [C:\ubuntu\js\platform-js\node_mo dules\sypexgeo-vyvid\build\sypexgeo.vcxproj]
..\src\xyz\vyvid\sypexgeo\bindings\nodejs\sypexgeo_node.cc(49): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EH sc [C:\ubuntu\js\platform-js\node_modules\sypexgeo-vyvid\build\sypexgeo.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dima\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dima\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ubuntu\js\platform-js\node_modules\sypexgeo-vyvid
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dima\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "sypexgeo-vyvid"
npm ERR! node v7.8.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! sypexgeo-vyvid@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sypexgeo-vyvid@0.2.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sypexgeo-vyvid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sypexgeo-vyvid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sypexgeo-vyvid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ubuntu\js\platform-js\npm-debug.log
```

**Comment by vsuharnikov** [comment]
Видел похожие ошибки в https://github.com/nodejs/node-gyp , в выходные постараюсь разобраться.

PS: не пришли уведомления от github :(

**Comment by vsuharnikov** [comment]
@terbooter Попробовал поставить nodejs на ievm (бесплатный образ от Microsoft с различными Windows/IE). Оказалось, что не хватает python, поставил его, дальше попытался поставить MS SDK, но похоже, необходимый VCBuild не поставился. Попробовал поставить MS Visual Studio 2008 C++ Express (ISO-образ с сайта MS), но он не ставится (ошибка по адресу…).

Короче говоря, я не готов потратить столько времени на Windows, учитывая, что работаю только в macOS и Linux. Но если вы разберетесь в проблеме, и сделаете pull request, я с радостью:
1. Сделаю ревью
2. Адаптирую изменения под macos и linux
3. Приму его

Пока что поправлю описание, что пакет не собирается под Windows.
